var title = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'Bastian Aichner: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/aichner_bastian/minute_shape', 'Bastian Aichner: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/aichner_bastian/minute_typo', 'Bastian Aichner: Eine Minute (Typographie)'],
    ['Block_I/A/baessler_stefan/minute_color', 'Stefan Baessler: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/baessler_stefan/minute_shape', 'Stefan Baessler: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/baessler_stefan/minute_typo', 'Stefan Baessler: Eine Minute (Typographie)'],
    ['Block_I/A/binder_lisa/minute_color', 'Lisa Binder: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/binder_lisa/minute_shape', 'Lisa Binder: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/binder_lisa/minute_typo', 'Lisa Binder: Eine Minute (Typographie)'],
    ['Block_I/A/breitenbach_petra/minute_color', 'Petra Breitenbach: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/breitenbach_petra/minute_shape', 'Petra Breitenbach: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/breitenbach_petra/minute_typo', 'Petra Breitenbach: Eine Minute (Typographie)'],
    ['Block_I/A/breunig_maximilian/minute_color', 'Maximilian Breunig: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/breunig_maximilian/minute_shape', 'Maximilian Breunig: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/breunig_maximilian/minute_typo', 'Maximilian Breunig: Eine Minute (Typographie)'],
    ['Block_I/A/bui_viet-duc/minute_color', 'Viet-Duc Bui: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/bui_viet-duc/minute_shape', 'Viet-Duc Bui: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/bui_viet-duc/minute_typo', 'Viet-Duc Bui: Eine Minute (Typographie)'],
    ['Block_I/A/christmann_tomas/minute_color', 'Tomas Christmann: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/christmann_tomas/minute_shape', 'Tomas Christmann: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/christmann_tomas/minute_typo', 'Tomas Christmann: Eine Minute (Typographie)'],
    ['Block_I/A/dieminger_annika/minute_color', 'Annika Dieminger: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/dieminger_annika/minute_shape', 'Annika Dieminger: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/dieminger_annika/minute_typo', 'Annika Dieminger: Eine Minute (Typographie)'],
    ['Block_I/A/domberger_ludwig/minute_shape', 'Ludwig Domberger: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/domberger_ludwig/minute_typo', 'Ludwig Domberger: Eine Minute (Typographie)'],
    ['Block_I/A/fleischmann_anna/minute_color', 'Anna Fleischmann: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/fleischmann_anna/minute_shape', 'Anna Fleischmann: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/fleischmann_anna/minute_typo', 'Anna Fleischmann: Eine Minute (Typographie)'],
    ['Block_I/A/fliehmann_lea/minute_color', 'Lea Fliehmann: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/fliehmann_lea/minute_shape', 'Lea Fliehmann: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/fliehmann_lea/minute_typo', 'Lea Fliehmann: Eine Minute (Typographie)'],
    ['Block_I/A/fritz_nicole/minute_color', 'Nicole Fritz: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/fritz_nicole/minute_shape', 'Nicole Fritz: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/fritz_nicole/minute_typo', 'Nicole Fritz: Eine Minute (Typographie)'],
    ['Block_I/A/friz_svea/minute_color', 'Svea Friz: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/friz_svea/minute_shape', 'Svea Friz: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/friz_svea/minute_typo', 'Svea Friz: Eine Minute (Typographie)'],
    ['Block_I/A/halang_sarah/minute_color', 'Sarah Halang: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/halang_sarah/minute_shape', 'Sarah Halang: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/halang_sarah/minute_typo', 'Sarah Halang: Eine Minute (Typographie)'],
    ['Block_I/A/hartmann_jule/minute_color', 'Jule Hartmann: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/hartmann_jule/minute_shape', 'Jule Hartmann: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/hartmann_jule/minute_typo', 'Jule Hartmann: Eine Minute (Typographie)],'],
    ['Block_I/A/haslauer_sarah/minute_color', 'Sarah Haslauer: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/haslauer_sarah/minute_shape', 'Sarah Haslauer: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/haslauer_sarah/minute_typo', 'Sarah Haslauer: Eine Minute (Typographie)'],
    ['Block_I/A/held_annika/minute_color', 'Annika Held: Eine Minute (Farbe/Kontrast)'],
    ['Block_I/A/held_annika/minute_shape', 'Annika Held: Eine Minute (Punkt/Linie/Fläche)'],
    ['Block_I/A/held_annika/minute_typo', 'Annika Held: Eine Minute (Typographie)'],
    ['Block_I/C/kaufmann_klaus/minute_x', 'Klaus Kaufmann: Linien und Wellen'],
    ['Block_I/C/scala_jan/minute_x', 'Jan Scala: Cubes'],
    ['Block_I/C/schlundt_daniel/minute_x', 'Daniel Schlundt: Neural Branches'],
    ['Block_I/C/schoenemann_lea/minute_x', 'Lea Schoenemann: Flower Waves'],
    ['Block_I/C/schulz_daniel/minute_x', 'Daniel Schulz: Endlose Spirale'],
    ['Block_I/C/semlinger_julia/minute_x', 'Julia Semlinger: movingpatterns'],
    ['Block_I/C/simon_lara/minute_x', 'Lara Simon: New Flow'],
    ['Block_I/C/thoma_marie/minute_x', 'Marie Thoma: Mindstorm'],
    ['Block_I/C/trinkl_simon/minute_x', 'Simon Trinkl: Blue Mountains'],
    ['Block_I/C/truger_timo/minute_x', 'Timo Truger: Pastel Regen'],
    ['Block_I/C/wagner_dennis/minute_x', 'Dennis Wagner: Kernfusion'],
    ['Block_I/C/wehner_romina/minute_x', 'Romina Wehner: Ausgemalt so wie ein Mandala'],
    ['Block_I/C/weiser_julia/minute_x', 'Julia Weiser: Color Clock'],
    ['Block_I/C/wiedemann_florian/minute_x', 'Florian Wiedemann: Balloons in the Sky'],
    ['Block_I/C/winatschek_marcel/minute_x', 'Marcel Winatschek: Die asketische Uhr'],
    ['Block_I/C/wonka_sophia/minute_x', 'Sophia Wonka: CLOCKWORKS'],
    ['Block_I/C/zettelmann_kay/minute_x', 'Kay Zettelmann: Abstract Clock'],

    ['Block_II/A/aichner_bastian/miniaturen/pull', 'Bastian Aichner: Ziehen'],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'Bastian Aichner: Drücken'],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'Bastian Aichner: Drehen'],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'Stefan Baessler: Ziehen'],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'Stefan Baessler: Drücken'],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'Stefan Baessler: Drehen'],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'Lisa Binder: Ziehen'],
    ['Block_II/A/binder_lisa/miniaturen/push', 'Lisa Binder: Drücken'],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'Lisa Binder: Drehen'],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'Petra Breitenbach: Ziehen'],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'Petra Breitenbach: Drücken'],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'Petra Breitenbach: Drehen'],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'Maximilian Breunig: Ziehen'],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'Maximilian Breunig: Drücken'],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'Viet-Duc Bui: Ziehen'],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'Viet-Duc Bui: Drücken'],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'Viet-Duc Bui: Drehen'],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'Tomas Christmann: Ziehen'],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'Tomas Christmann: Drücken'],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'Tomas Christmann: Drehen'],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'Annika Dieminger: Ziehen'],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'Annika Dieminger: Drücken'],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'Annika Dieminger: Drehen'],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'Ludwig Domberger: Ziehen'],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'Ludwig Domberger: Drücken'],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'Ludwig Domberger: Drehen'],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'Anna Fleischmann: Ziehen'],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'Anna Fleischmann: Drücken'],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'Anna Fleischmann: Drehen'],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'Lea Fliehmann: Ziehen'],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'Lea Fliehmann: Drücken'],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'Lea Fliehmann: Drehen'],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'Nicole Fritz: Ziehen '],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'Nicole Fritz: Drücken'],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'Nicole Fritz: Drehen'],
    ['Block_II/A/friz_svea/miniaturen/pull', 'Svea Friz: Ziehen '],
    ['Block_II/A/friz_svea/miniaturen/turn', 'Svea Friz: Drehen'],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'Sarah Halang: Ziehen'],
    ['Block_II/A/halang_sarah/miniaturen/push', 'Sarah Halang: Drücken'],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'Sarah Halang: Drehen'],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'Jule Hartmann: Ziehen'],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'Jule Hartmann: Drücken'],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'Jule Hartmann: Drehen'],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'Sarah Haslauer: Ziehen'],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'Sarah Haslauer: Drücken'],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'Sarah Haslauer: Drehen'],
    ['Block_II/A/held_annika/miniaturen/pull', 'Annika Held: Ziehen'],
    ['Block_II/A/held_annika/miniaturen/push', 'Annika Held: Drücken'],
    ['Block_II/A/held_annika/miniaturen/turn', 'Annika Held: Drehen'],
    ['Block_II/C/kaufmann_klaus/miniaturen/press', 'Klaus Kaufmann: Drücken'],
    ['Block_II/C/scala_jan/miniaturen/pull', 'Jan Scala: Ziehen'],
    ['Block_II/C/schaffer_marco/miniaturen/pull', 'Marco Schaffer: Ziehen'],
    ['Block_II/C/schlundt_daniel/miniaturen/press', 'Daniel Schlundt: Drücken '],

    ['Block_II/A/aichner_bastian/ticktack', 'Bastian Aichner: Tick Tack Bombe'],
    ['Block_II/A/baessler_stefan/ticktack', 'Stefan Baessler: BPM Match'],
    ['Block_II/A/binder_lisa/ticktack', 'Lisa Binder: Pendulum'],
    ['Block_II/A/breitenbach_petra/ticktack', 'Petra Breitenbach: 30 Clicks'],
    ['Block_II/A/breunig_maximilian/ticktack', 'Maximilian Breunig: Type-Tack'],
    ['Block_II/A/bui_viet-duc/ticktack', 'Viet-duc Bui: Tick-Tack'],
    ['Block_II/A/christmann_tomas/ticktack', 'Tomas Christmann: BPM Tapper'],
    ['Block_II/A/dieminger_annika/ticktack', 'Annika Dieminger: TikTak'],
    ['Block_II/A/domberger_ludwig/ticktack', 'Ludwig Domberger: TickTack'],
    ['Block_II/A/fleischmann_anna/ticktack', 'Anna Fleischmann: Tik Tak'],
    ['Block_II/A/fliehmann_lea/ticktack', 'Lea Fliehmann: Tick Tack'],
    ['Block_II/A/fritz_nicole/ticktack', 'Nicole Fritz: Tick Tack'],
    ['Block_II/A/friz_svea/ticktack', 'Svea Friz: Tick-Tack'],
    ['Block_II/A/halang_sarah/ticktack', 'Sarah Halang: TICK-TACK'],
    ['Block_II/A/hartmann_jule/ticktack', 'Jule Hartmann: TickTack!'],
    ['Block_II/A/haslauer_sarah/ticktack', 'Sarah Haslauer: TickTack'],
    ['Block_II/A/held_annika/ticktack', 'Annika Held: Tick Tack'],
    ['Block_II/C/schaffer_marco/ticktack', 'Marco Schaffer: Emotionsplayer'],
    ['Block_II/C/schneider_lisa/ticktack', 'Lisa Schneider: Color Your Motion'],
    ['Block_II/C/schoenemann_lea/ticktack', 'Lea Schönemann: berrytree'],
    ['Block_II/C/schulz_daniel/ticktack', 'Daniel Schulz: SpaceDrummer'],
    ['Block_II/C/semlinger_julia/ticktack', 'Julia Semlinger: Move it'],
    ['Block_II/C/thoma_marie/ticktack', 'Marie Thoma: Strawberry Catch'],
    ['Block_II/C/trinkl_simon/ticktack', 'Simon Trinkl: Lovely Sounds'],
    ['Block_II/C/wagner_dennis/ticktack', 'Dennis Wagner: Fishin\' Impossible'],
    ['Block_II/C/wehner_romina/ticktack', 'Romina Wehner: Headshot'],
    ['Block_II/C/wiedemann_florian/ticktack', 'Florian Wiedemann: Running Walls'],
    ['Block_II/C/winatschek_marcel/ticktack', 'Marcel Winatschek: Stay Fucking Happy!'],
    ['Block_II/C/wonka_sophia/ticktack', 'Sophia Wonka: digital emotion mirror'],
    ['Block_II/C/zettelmann_kay/ticktack', 'Kay Zettelmann: INTO THE DEEP'],

    ['Block_I/B/heidle_lena', 'Lena Heidle: Buchverkauf pro Minute'],
    ['Block_I/B/heinrich_finn', 'Finn Heinrich: Weather\'s Canvas'],
    ['Block_I/B/henke_michael', 'Michael Henke: Click per Minute'],
    ['Block_I/B/hornung_tara', 'Tara Hornung: Zeit als Prozess'],
    ['Block_I/B/just_ann-kathrin', 'Ann-Kathrin Just: Lenkung der Gedanken'],
    ['Block_I/B/kleiner_tobias', 'Tobias Kleiner: People in Space'],
    ['Block_I/B/kurzmann_paul', 'Paul Kurzmann: One more Step'],
    ['Block_I/B/litzel_christian', 'Christian Litzel: Puls'],
    ['Block_I/B/macijauskaite_iveta', 'Iveta Macijauskaite: Unser Leben hängt vom Luftstrom ab'],
    ['Block_I/B/mayr_marie', 'Marie Mayr: Minuten Knaller'],
    ['Block_I/B/pohl_jessica', 'Jessica Pohl: Sound Circle'],
    ['Block_I/B/roemmelt_alina', 'Alina Römmelt: Planeten'],
]);
var ffw   = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'Block_I/A/aichner_bastian/minute_shape'],
    ['Block_I/A/aichner_bastian/minute_shape', 'Block_I/A/aichner_bastian/minute_typo'],
    ['Block_I/A/aichner_bastian/minute_typo', 'Block_I/A/baessler_stefan/minute_color'],
    ['Block_I/A/baessler_stefan/minute_color', 'Block_I/A/baessler_stefan/minute_shape'],
    ['Block_I/A/baessler_stefan/minute_shape', 'Block_I/A/baessler_stefan/minute_typo'],
    ['Block_I/A/baessler_stefan/minute_typo', 'Block_I/A/binder_lisa/minute_color'],
    ['Block_I/A/binder_lisa/minute_color', 'Block_I/A/binder_lisa/minute_shape'],
    ['Block_I/A/binder_lisa/minute_shape', 'Block_I/A/binder_lisa/minute_typo'],
    ['Block_I/A/binder_lisa/minute_typo', 'Block_I/A/breitenbach_petra/minute_color'],
    ['Block_I/A/breitenbach_petra/minute_color', 'Block_I/A/breitenbach_petra/minute_shape'],
    ['Block_I/A/breitenbach_petra/minute_shape', 'Block_I/A/breitenbach_petra/minute_typo'],
    ['Block_I/A/breitenbach_petra/minute_typo', 'Block_I/A/breunig_maximilian/minute_color'],
    ['Block_I/A/breunig_maximilian/minute_color', 'Block_I/A/breunig_maximilian/minute_shape'],
    ['Block_I/A/breunig_maximilian/minute_shape', 'Block_I/A/breunig_maximilian/minute_typo'],
    ['Block_I/A/breunig_maximilian/minute_typo', 'Block_I/A/bui_viet-duc/minute_color'],
    ['Block_I/A/bui_viet-duc/minute_color', 'Block_I/A/bui_viet-duc/minute_shape'],
    ['Block_I/A/bui_viet-duc/minute_shape', 'Block_I/A/bui_viet-duc/minute_typo'],
    ['Block_I/A/bui_viet-duc/minute_typo', 'Block_I/A/christmann_tomas/minute_color'],
    ['Block_I/A/christmann_tomas/minute_color', 'Block_I/A/christmann_tomas/minute_shape'],
    ['Block_I/A/christmann_tomas/minute_shape', 'Block_I/A/christmann_tomas/minute_typo'],
    ['Block_I/A/christmann_tomas/minute_typo', 'Block_I/A/dieminger_annika/minute_color'],
    ['Block_I/A/dieminger_annika/minute_color', 'Block_I/A/dieminger_annika/minute_shape'],
    ['Block_I/A/dieminger_annika/minute_shape', 'Block_I/A/dieminger_annika/minute_typo'],
    ['Block_I/A/dieminger_annika/minute_typo', 'Block_I/A/domberger_ludwig/minute_shape'],
    ['Block_I/A/domberger_ludwig/minute_shape', 'Block_I/A/domberger_ludwig/minute_typo'],
    ['Block_I/A/domberger_ludwig/minute_typo', 'Block_I/A/fleischmann_anna/minute_color'],
    ['Block_I/A/fleischmann_anna/minute_color', 'Block_I/A/fleischmann_anna/minute_shape'],
    ['Block_I/A/fleischmann_anna/minute_shape', 'Block_I/A/fleischmann_anna/minute_typo'],
    ['Block_I/A/fleischmann_anna/minute_typo', 'Block_I/A/fliehmann_lea/minute_color'],
    ['Block_I/A/fliehmann_lea/minute_color', 'Block_I/A/fliehmann_lea/minute_shape'],
    ['Block_I/A/fliehmann_lea/minute_shape', 'Block_I/A/fliehmann_lea/minute_typo'],
    ['Block_I/A/fliehmann_lea/minute_typo', 'Block_I/A/fritz_nicole/minute_color'],
    ['Block_I/A/fritz_nicole/minute_color', 'Block_I/A/fritz_nicole/minute_shape'],
    ['Block_I/A/fritz_nicole/minute_shape', 'Block_I/A/fritz_nicole/minute_typo'],
    ['Block_I/A/fritz_nicole/minute_typo', 'Block_I/A/friz_svea/minute_color'],
    ['Block_I/A/friz_svea/minute_color', 'Block_I/A/friz_svea/minute_shape'],
    ['Block_I/A/friz_svea/minute_shape', 'Block_I/A/friz_svea/minute_typo'],
    ['Block_I/A/friz_svea/minute_typo', 'Block_I/A/halang_sarah/minute_color'],
    ['Block_I/A/halang_sarah/minute_color', 'Block_I/A/halang_sarah/minute_shape'],
    ['Block_I/A/halang_sarah/minute_shape', 'Block_I/A/halang_sarah/minute_typo'],
    ['Block_I/A/halang_sarah/minute_typo', 'Block_I/A/hartmann_jule/minute_color'],
    ['Block_I/A/hartmann_jule/minute_color', 'Block_I/A/hartmann_jule/minute_shape'],
    ['Block_I/A/hartmann_jule/minute_shape', 'Block_I/A/hartmann_jule/minute_typo'],
    ['Block_I/A/hartmann_jule/minute_typo', 'Block_I/A/haslauer_sarah/minute_color'],
    ['Block_I/A/haslauer_sarah/minute_color', 'Block_I/A/haslauer_sarah/minute_shape'],
    ['Block_I/A/haslauer_sarah/minute_shape', 'Block_I/A/haslauer_sarah/minute_typo'],
    ['Block_I/A/haslauer_sarah/minute_typo', 'Block_I/A/held_annika/minute_color'],
    ['Block_I/A/held_annika/minute_color', 'Block_I/A/held_annika/minute_shape'],
    ['Block_I/A/held_annika/minute_shape', 'Block_I/A/held_annika/minute_typo'],
    ['Block_I/A/held_annika/minute_typo', 'Block_I/C/kaufmann_klaus/minute_x'],
    ['Block_I/C/kaufmann_klaus/minute_x', 'Block_I/C/scala_jan/minute_x'],
    ['Block_I/C/scala_jan/minute_x', 'Block_I/C/schlundt_daniel/minute_x'],
    ['Block_I/C/schlundt_daniel/minute_x', 'Block_I/C/schoenemann_lea/minute_x'],
    ['Block_I/C/schoenemann_lea/minute_x', 'Block_I/C/schulz_daniel/minute_x'],
    ['Block_I/C/schulz_daniel/minute_x', 'Block_I/C/semlinger_julia/minute_x'],
    ['Block_I/C/semlinger_julia/minute_x', 'Block_I/C/simon_lara/minute_x'],
    ['Block_I/C/simon_lara/minute_x', 'Block_I/C/thoma_marie/minute_x'],
    ['Block_I/C/thoma_marie/minute_x', 'Block_I/C/trinkl_simon/minute_x'],
    ['Block_I/C/trinkl_simon/minute_x', 'Block_I/C/truger_timo/minute_x'],
    ['Block_I/C/truger_timo/minute_x', 'Block_I/C/wagner_dennis/minute_x'],
    ['Block_I/C/wagner_dennis/minute_x', 'Block_I/C/wehner_romina/minute_x'],
    ['Block_I/C/wehner_romina/minute_x', 'Block_I/C/weiser_julia/minute_x'],
    ['Block_I/C/weiser_julia/minute_x', 'Block_I/C/wiedemann_florian/minute_x'],
    ['Block_I/C/wiedemann_florian/minute_x', 'Block_I/C/winatschek_marcel/minute_x'],
    ['Block_I/C/winatschek_marcel/minute_x', 'Block_I/C/wonka_sophia/minute_x'],
    ['Block_I/C/wonka_sophia/minute_x', 'Block_I/C/zettelmann_kay/minute_x'],
    ['Block_I/C/zettelmann_kay/minute_x', 'Block_I/A/aichner_bastian/minute_color'],
    ['Block_II/A/aichner_bastian/miniaturen/pull', 'Block_II/A/aichner_bastian/miniaturen/push'],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'Block_II/A/aichner_bastian/miniaturen/turn'],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'Block_II/A/baessler_stefan/miniaturen/pull'],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'Block_II/A/baessler_stefan/miniaturen/push'],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'Block_II/A/baessler_stefan/miniaturen/turn'],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'Block_II/A/binder_lisa/miniaturen/pull'],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'Block_II/A/binder_lisa/miniaturen/push'],
    ['Block_II/A/binder_lisa/miniaturen/push', 'Block_II/A/binder_lisa/miniaturen/turn'],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'Block_II/A/breitenbach_petra/miniaturen/pull'],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'Block_II/A/breitenbach_petra/miniaturen/push'],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'Block_II/A/breitenbach_petra/miniaturen/turn'],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'Block_II/A/breunig_maximilian/miniaturen/pull'],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'Block_II/A/breunig_maximilian/miniaturen/push'],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'Block_II/A/bui_viet-duc/miniaturen/push'],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'Block_II/A/bui_viet-duc/miniaturen/push'],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'Block_II/A/bui_viet-duc/miniaturen/turn'],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'Block_II/A/christmann_tomas/miniaturen/pull'],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'Block_II/A/christmann_tomas/miniaturen/push'],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'Block_II/A/christmann_tomas/miniaturen/turn'],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'Block_II/A/dieminger_annika/miniaturen/pull'],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'Block_II/A/dieminger_annika/miniaturen/push'],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'Block_II/A/dieminger_annika/miniaturen/turn'],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'Block_II/A/domberger_ludwig/miniaturen/pull'],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'Block_II/A/domberger_ludwig/miniaturen/push'],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'Block_II/A/domberger_ludwig/miniaturen/turn'],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'Block_II/A/fleischmann_anna/miniaturen/pull'],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'Block_II/A/fleischmann_anna/miniaturen/push'],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'Block_II/A/fleischmann_anna/miniaturen/turn'],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'Block_II/A/fliehmann_lea/miniaturen/pull'],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'Block_II/A/fliehmann_lea/miniaturen/push'],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'Block_II/A/fliehmann_lea/miniaturen/turn'],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'Block_II/A/fritz_nicole/miniaturen/pull'],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'Block_II/A/fritz_nicole/miniaturen/push'],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'Block_II/A/fritz_nicole/miniaturen/turn'],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'Block_II/A/friz_svea/miniaturen/pull'],
    ['Block_II/A/friz_svea/miniaturen/pull', 'Block_II/A/friz_svea/miniaturen/turn'],
    ['Block_II/A/friz_svea/miniaturen/turn', 'Block_II/A/halang_sarah/miniaturen/push'],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'Block_II/A/halang_sarah/miniaturen/push'],
    ['Block_II/A/halang_sarah/miniaturen/push', 'Block_II/A/halang_sarah/miniaturen/turn'],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'Block_II/A/hartmann_jule/miniaturen/pull'],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'Block_II/A/hartmann_jule/miniaturen/push'],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'Block_II/A/hartmann_jule/miniaturen/turn'],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'Block_II/A/haslauer_sarah/miniaturen/pull'],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'Block_II/A/haslauer_sarah/miniaturen/push'],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'Block_II/A/haslauer_sarah/miniaturen/turn'],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'Block_II/A/held_annika/miniaturen/pull'],
    ['Block_II/A/held_annika/miniaturen/pull', 'Block_II/A/held_annika/miniaturen/push'],
    ['Block_II/A/held_annika/miniaturen/push', 'Block_II/A/held_annika/miniaturen/turn'],
    ['Block_II/A/held_annika/miniaturen/turn', 'Block_II/C/kaufmann_klaus/miniaturen/press'],
    ['Block_II/C/kaufmann_klaus/miniaturen/press', 'Block_II/C/scala_jan/miniaturen/pull'],
    ['Block_II/C/scala_jan/miniaturen/pull', 'Block_II/C/schaffer_marco/miniaturen/pull'],
    ['Block_II/C/schaffer_marco/miniaturen/pull', 'Block_II/C/schlundt_daniel/miniaturen/press'],
    ['Block_II/C/schlundt_daniel/miniaturen/press', 'Block_II/A/aichner_bastian/miniaturen/pull'],
    ['Block_II/A/aichner_bastian/ticktack', 'Block_II/A/baessler_stefan/ticktack'],
    ['Block_II/A/baessler_stefan/ticktack', 'Block_II/A/binder_lisa/ticktack'],
    ['Block_II/A/binder_lisa/ticktack', 'Block_II/A/breitenbach_petra/ticktack'],
    ['Block_II/A/breitenbach_petra/ticktack', 'Block_II/A/breunig_maximilian/ticktack'],
    ['Block_II/A/breunig_maximilian/ticktack', 'Block_II/A/bui_viet-duc/ticktack'],
    ['Block_II/A/bui_viet-duc/ticktack', 'Block_II/A/christmann_tomas/ticktack'],
    ['Block_II/A/christmann_tomas/ticktack', 'Block_II/A/dieminger_annika/ticktack'],
    ['Block_II/A/dieminger_annika/ticktack', 'Block_II/A/domberger_ludwig/ticktack'],
    ['Block_II/A/domberger_ludwig/ticktack', 'Block_II/A/fleischmann_anna/ticktack'],
    ['Block_II/A/fleischmann_anna/ticktack', 'Block_II/A/fliehmann_lea/ticktack'],
    ['Block_II/A/fliehmann_lea/ticktack', 'Block_II/A/fritz_nicole/ticktack'],
    ['Block_II/A/fritz_nicole/ticktack', 'Block_II/A/friz_svea/ticktack'],
    ['Block_II/A/friz_svea/ticktack', 'Block_II/A/halang_sarah/ticktack'],
    ['Block_II/A/halang_sarah/ticktack', 'Block_II/A/hartmann_jule/ticktack'],
    ['Block_II/A/hartmann_jule/ticktack', 'Block_II/A/haslauer_sarah/ticktack'],
    ['Block_II/A/haslauer_sarah/ticktack', 'Block_II/A/held_annika/ticktack'],
    ['Block_II/A/held_annika/ticktack', 'Block_II/C/schaffer_marco/ticktack'],
    ['Block_II/C/schaffer_marco/ticktack', 'Block_II/C/schneider_lisa/ticktack'],
    ['Block_II/C/schneider_lisa/ticktack', 'Block_II/C/schoenemann_lea/ticktack'],
    ['Block_II/C/schoenemann_lea/ticktack', 'Block_II/C/schulz_daniel/ticktack'],
    ['Block_II/C/schulz_daniel/ticktack', 'Block_II/C/semlinger_julia/ticktack'],
    ['Block_II/C/semlinger_julia/ticktack', 'Block_II/C/thoma_marie/ticktack'],
    ['Block_II/C/thoma_marie/ticktack', 'Block_II/C/trinkl_simon/ticktack'],
    ['Block_II/C/trinkl_simon/ticktack', 'Block_II/C/wagner_dennis/ticktack'],
    ['Block_II/C/wagner_dennis/ticktack', 'Block_II/C/wehner_romina/ticktack'],
    ['Block_II/C/wehner_romina/ticktack', 'Block_II/C/wiedemann_florian/ticktack'],
    ['Block_II/C/wiedemann_florian/ticktack', 'Block_II/C/winatschek_marcel/ticktack'],
    ['Block_II/C/winatschek_marcel/ticktack', 'Block_II/C/wonka_sophia/ticktack'],
    ['Block_II/C/wonka_sophia/ticktack', 'Block_II/C/zettelmann_kay/ticktack'],
    ['Block_II/C/zettelmann_kay/ticktack', 'Block_II/A/aichner_bastian/ticktack'],
    ['Block_I/B/heidle_lena', 'Block_I/B/heinrich_finn'],
    ['Block_I/B/heinrich_finn', 'Block_I/B/henke_michael'],
    ['Block_I/B/henke_michael', 'Block_I/B/hornung_tara'],
    ['Block_I/B/hornung_tara', 'Block_I/B/just_ann-kathrin'],
    ['Block_I/B/just_ann-kathrin', 'Block_I/B/kleiner_tobias'],
    ['Block_I/B/kleiner_tobias', 'Block_I/B/kurzmann_paul'],
    ['Block_I/B/kurzmann_paul', 'Block_I/B/litzel_christian'],
    ['Block_I/B/litzel_christian', 'Block_I/B/macijauskaite_iveta'],
    ['Block_I/B/macijauskaite_iveta', 'Block_I/B/mayr_marie'],
    ['Block_I/B/mayr_marie', 'Block_I/B/pohl_jessica'],
    ['Block_I/B/pohl_jessica', 'Block_I/B/roemmelt_alina'],
    ['Block_I/B/roemmelt_alina', 'Block_I/B/heidle_lena'],
]);
var rew   = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'Block_I/C/zettelmann_kay/minute_x'],
    ['Block_I/A/aichner_bastian/minute_shape', 'Block_I/A/aichner_bastian/minute_color'],
    ['Block_I/A/aichner_bastian/minute_typo', 'Block_I/A/aichner_bastian/minute_shape'],
    ['Block_I/A/baessler_stefan/minute_color', 'Block_I/A/aichner_bastian/minute_typo'],
    ['Block_I/A/baessler_stefan/minute_shape', 'Block_I/A/baessler_stefan/minute_color'],
    ['Block_I/A/baessler_stefan/minute_typo', 'Block_I/A/baessler_stefan/minute_shape'],
    ['Block_I/A/binder_lisa/minute_color', 'Block_I/A/baessler_stefan/minute_typo'],
    ['Block_I/A/binder_lisa/minute_shape', 'Block_I/A/binder_lisa/minute_color'],
    ['Block_I/A/binder_lisa/minute_typo', 'Block_I/A/binder_lisa/minute_shape'],
    ['Block_I/A/breitenbach_petra/minute_color', 'Block_I/A/binder_lisa/minute_typo'],
    ['Block_I/A/breitenbach_petra/minute_shape', 'Block_I/A/breitenbach_petra/minute_color'],
    ['Block_I/A/breitenbach_petra/minute_typo', 'Block_I/A/breitenbach_petra/minute_shape'],
    ['Block_I/A/breunig_maximilian/minute_color', 'Block_I/A/breitenbach_petra/minute_typo'],
    ['Block_I/A/breunig_maximilian/minute_shape', 'Block_I/A/breunig_maximilian/minute_color'],
    ['Block_I/A/breunig_maximilian/minute_typo', 'Block_I/A/breunig_maximilian/minute_shape'],
    ['Block_I/A/bui_viet-duc/minute_color', 'Block_I/A/breunig_maximilian/minute_typo'],
    ['Block_I/A/bui_viet-duc/minute_shape', 'Block_I/A/bui_viet-duc/minute_color'],
    ['Block_I/A/bui_viet-duc/minute_typo', 'Block_I/A/bui_viet-duc/minute_shape'],
    ['Block_I/A/christmann_tomas/minute_color', 'Block_I/A/bui_viet-duc/minute_typo'],
    ['Block_I/A/christmann_tomas/minute_shape', 'Block_I/A/christmann_tomas/minute_color'],
    ['Block_I/A/christmann_tomas/minute_typo', 'Block_I/A/christmann_tomas/minute_shape'],
    ['Block_I/A/dieminger_annika/minute_color', 'Block_I/A/christmann_tomas/minute_typo'],
    ['Block_I/A/dieminger_annika/minute_shape', 'Block_I/A/dieminger_annika/minute_color'],
    ['Block_I/A/dieminger_annika/minute_typo', 'Block_I/A/dieminger_annika/minute_shape'],
    ['Block_I/A/domberger_ludwig/minute_shape', 'Block_I/A/dieminger_annika/minute_typo'],
    ['Block_I/A/domberger_ludwig/minute_typo', 'Block_I/A/domberger_ludwig/minute_shape'],
    ['Block_I/A/fleischmann_anna/minute_color', 'Block_I/A/domberger_ludwig/minute_typo'],
    ['Block_I/A/fleischmann_anna/minute_shape', 'Block_I/A/fleischmann_anna/minute_color'],
    ['Block_I/A/fleischmann_anna/minute_typo', 'Block_I/A/fleischmann_anna/minute_shape'],
    ['Block_I/A/fliehmann_lea/minute_color', 'Block_I/A/fleischmann_anna/minute_typo'],
    ['Block_I/A/fliehmann_lea/minute_shape', 'Block_I/A/fliehmann_lea/minute_color'],
    ['Block_I/A/fliehmann_lea/minute_typo', 'Block_I/A/fliehmann_lea/minute_shape'],
    ['Block_I/A/fritz_nicole/minute_color', 'Block_I/A/fliehmann_lea/minute_typo'],
    ['Block_I/A/fritz_nicole/minute_shape', 'Block_I/A/fritz_nicole/minute_color'],
    ['Block_I/A/fritz_nicole/minute_typo', 'Block_I/A/fritz_nicole/minute_shape'],
    ['Block_I/A/friz_svea/minute_color', 'Block_I/A/fritz_nicole/minute_typo'],
    ['Block_I/A/friz_svea/minute_shape', 'Block_I/A/friz_svea/minute_color'],
    ['Block_I/A/friz_svea/minute_typo', 'Block_I/A/friz_svea/minute_shape'],
    ['Block_I/A/halang_sarah/minute_color', 'Block_I/A/friz_svea/minute_typo'],
    ['Block_I/A/halang_sarah/minute_shape', 'Block_I/A/halang_sarah/minute_color'],
    ['Block_I/A/halang_sarah/minute_typo', 'Block_I/A/halang_sarah/minute_shape'],
    ['Block_I/A/hartmann_jule/minute_color', 'Block_I/A/halang_sarah/minute_typo'],
    ['Block_I/A/hartmann_jule/minute_shape', 'Block_I/A/hartmann_jule/minute_color'],
    ['Block_I/A/hartmann_jule/minute_typo', 'Block_I/A/hartmann_jule/minute_shape'],
    ['Block_I/A/haslauer_sarah/minute_color', 'Block_I/A/hartmann_jule/minute_typo'],
    ['Block_I/A/haslauer_sarah/minute_shape', 'Block_I/A/haslauer_sarah/minute_color'],
    ['Block_I/A/haslauer_sarah/minute_typo', 'Block_I/A/haslauer_sarah/minute_shape'],
    ['Block_I/A/held_annika/minute_color', 'Block_I/A/haslauer_sarah/minute_typo'],
    ['Block_I/A/held_annika/minute_shape', 'Block_I/A/held_annika/minute_color'],
    ['Block_I/A/held_annika/minute_typo', 'Block_I/A/held_annika/minute_shape'],
    ['Block_I/C/kaufmann_klaus/minute_x', 'Block_I/A/held_annika/minute_typo'],
    ['Block_I/C/scala_jan/minute_x', 'Block_I/C/kaufmann_klaus/minute_x'],
    ['Block_I/C/schlundt_daniel/minute_x', 'Block_I/C/scala_jan/minute_x'],
    ['Block_I/C/schoenemann_lea/minute_x', 'Block_I/C/schlundt_daniel/minute_x'],
    ['Block_I/C/schulz_daniel/minute_x', 'Block_I/C/schoenemann_lea/minute_x'],
    ['Block_I/C/semlinger_julia/minute_x', 'Block_I/C/schulz_daniel/minute_x'],
    ['Block_I/C/simon_lara/minute_x', 'Block_I/C/semlinger_julia/minute_x'],
    ['Block_I/C/thoma_marie/minute_x', 'Block_I/C/simon_lara/minute_x'],
    ['Block_I/C/trinkl_simon/minute_x', 'Block_I/C/thoma_marie/minute_x'],
    ['Block_I/C/truger_timo/minute_x', 'Block_I/C/trinkl_simon/minute_x'],
    ['Block_I/C/wagner_dennis/minute_x', 'Block_I/C/truger_timo/minute_x'],
    ['Block_I/C/wehner_romina/minute_x', 'Block_I/C/wagner_dennis/minute_x'],
    ['Block_I/C/weiser_julia/minute_x', 'Block_I/C/wehner_romina/minute_x'],
    ['Block_I/C/wiedemann_florian/minute_x', 'Block_I/C/weiser_julia/minute_x'],
    ['Block_I/C/winatschek_marcel/minute_x', 'Block_I/C/wiedemann_florian/minute_x'],
    ['Block_I/C/wonka_sophia/minute_x', 'Block_I/C/winatschek_marcel/minute_x'],
    ['Block_I/C/zettelmann_kay/minute_x', 'Block_I/C/wonka_sophia/minute_x'],
    ['Block_II/A/aichner_bastian/miniaturen/pull', 'Block_II/C/schlundt_daniel/miniaturen/press'],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'Block_II/A/aichner_bastian/miniaturen/pull'],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'Block_II/A/aichner_bastian/miniaturen/push'],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'Block_II/A/aichner_bastian/miniaturen/turn'],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'Block_II/A/baessler_stefan/miniaturen/pull'],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'Block_II/A/baessler_stefan/miniaturen/push'],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'Block_II/A/baessler_stefan/miniaturen/turn'],
    ['Block_II/A/binder_lisa/miniaturen/push', 'Block_II/A/binder_lisa/miniaturen/pull'],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'Block_II/A/binder_lisa/miniaturen/push'],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'Block_II/A/binder_lisa/miniaturen/turn'],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'Block_II/A/breitenbach_petra/miniaturen/pull'],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'Block_II/A/breitenbach_petra/miniaturen/push'],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'Block_II/A/breitenbach_petra/miniaturen/turn'],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'Block_II/A/breunig_maximilian/miniaturen/pull'],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'Block_II/A/breunig_maximilian/miniaturen/pull'],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'Block_II/A/bui_viet-duc/miniaturen/pull'],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'Block_II/A/bui_viet-duc/miniaturen/push'],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'Block_II/A/bui_viet-duc/miniaturen/turn'],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'Block_II/A/christmann_tomas/miniaturen/pull'],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'Block_II/A/christmann_tomas/miniaturen/push'],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'Block_II/A/christmann_tomas/miniaturen/turn'],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'Block_II/A/dieminger_annika/miniaturen/pull'],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'Block_II/A/dieminger_annika/miniaturen/push'],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'Block_II/A/dieminger_annika/miniaturen/turn'],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'Block_II/A/domberger_ludwig/miniaturen/pull'],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'Block_II/A/domberger_ludwig/miniaturen/push'],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'Block_II/A/domberger_ludwig/miniaturen/turn'],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'Block_II/A/fleischmann_anna/miniaturen/pull'],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'Block_II/A/fleischmann_anna/miniaturen/push'],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'Block_II/A/fleischmann_anna/miniaturen/turn'],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'Block_II/A/fliehmann_lea/miniaturen/pull'],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'Block_II/A/fliehmann_lea/miniaturen/push'],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'Block_II/A/fliehmann_lea/miniaturen/turn'],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'Block_II/A/fritz_nicole/miniaturen/pull'],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'Block_II/A/fritz_nicole/miniaturen/push'],
    ['Block_II/A/friz_svea/miniaturen/pull', 'Block_II/A/fritz_nicole/miniaturen/turn'],
    ['Block_II/A/friz_svea/miniaturen/turn', 'Block_II/A/friz_svea/miniaturen/pull'],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'Block_II/A/friz_svea/miniaturen/turn'],
    ['Block_II/A/halang_sarah/miniaturen/push', 'Block_II/A/halang_sarah/miniaturen/pull'],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'Block_II/A/halang_sarah/miniaturen/push'],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'Block_II/A/halang_sarah/miniaturen/turn'],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'Block_II/A/hartmann_jule/miniaturen/pull'],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'Block_II/A/hartmann_jule/miniaturen/push'],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'Block_II/A/hartmann_jule/miniaturen/turn'],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'Block_II/A/haslauer_sarah/miniaturen/pull'],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'Block_II/A/haslauer_sarah/miniaturen/push'],
    ['Block_II/A/held_annika/miniaturen/pull', 'Block_II/A/haslauer_sarah/miniaturen/turn'],
    ['Block_II/A/held_annika/miniaturen/push', 'Block_II/A/held_annika/miniaturen/pull'],
    ['Block_II/A/held_annika/miniaturen/turn', 'Block_II/A/held_annika/miniaturen/push'],
    ['Block_II/C/kaufmann_klaus/miniaturen/press', 'Block_II/A/held_annika/miniaturen/turn'],
    ['Block_II/C/scala_jan/miniaturen/pull', 'Block_II/C/kaufmann_klaus/miniaturen/press'],
    ['Block_II/C/schaffer_marco/miniaturen/pull', 'Block_II/C/scala_jan/miniaturen/pull'],
    ['Block_II/C/schlundt_daniel/miniaturen/press', 'Block_II/C/schaffer_marco/miniaturen/pull'],
    ['Block_II/A/aichner_bastian/ticktack', 'Block_II/C/zettelmann_kay/ticktack'],
    ['Block_II/A/baessler_stefan/ticktack', 'Block_II/A/aichner_bastian/ticktack'],
    ['Block_II/A/binder_lisa/ticktack', 'Block_II/A/baessler_stefan/ticktack'],
    ['Block_II/A/breitenbach_petra/ticktack', 'Block_II/A/binder_lisa/ticktack'],
    ['Block_II/A/breunig_maximilian/ticktack', 'Block_II/A/breitenbach_petra/ticktack'],
    ['Block_II/A/bui_viet-duc/ticktack', 'Block_II/A/breunig_maximilian/ticktack'],
    ['Block_II/A/christmann_tomas/ticktack', 'Block_II/A/bui_viet-duc/ticktack'],
    ['Block_II/A/dieminger_annika/ticktack', 'Block_II/A/christmann_tomas/ticktack'],
    ['Block_II/A/domberger_ludwig/ticktack', 'Block_II/A/dieminger_annika/ticktack'],
    ['Block_II/A/fleischmann_anna/ticktack', 'Block_II/A/domberger_ludwig/ticktack'],
    ['Block_II/A/fliehmann_lea/ticktack', 'Block_II/A/fleischmann_anna/ticktack'],
    ['Block_II/A/fritz_nicole/ticktack', 'Block_II/A/fliehmann_lea/ticktack'],
    ['Block_II/A/friz_svea/ticktack', 'Block_II/A/fritz_nicole/ticktack'],
    ['Block_II/A/halang_sarah/ticktack', 'Block_II/A/friz_svea/ticktack'],
    ['Block_II/A/hartmann_jule/ticktack', 'Block_II/A/halang_sarah/ticktack'],
    ['Block_II/A/haslauer_sarah/ticktack', 'Block_II/A/hartmann_jule/ticktack'],
    ['Block_II/A/held_annika/ticktack', 'Block_II/A/haslauer_sarah/ticktack'],
    ['Block_II/C/schaffer_marco/ticktack', 'Block_II/A/held_annika/ticktack'],
    ['Block_II/C/schneider_lisa/ticktack', 'Block_II/C/schaffer_marco/ticktack'],
    ['Block_II/C/schoenemann_lea/ticktack', 'Block_II/C/schneider_lisa/ticktack'],
    ['Block_II/C/schulz_daniel/ticktack', 'Block_II/C/schoenemann_lea/ticktack'],
    ['Block_II/C/semlinger_julia/ticktack', 'Block_II/C/schulz_daniel/ticktack'],
    ['Block_II/C/thoma_marie/ticktack', 'Block_II/C/semlinger_julia/ticktack'],
    ['Block_II/C/trinkl_simon/ticktack', 'Block_II/C/thoma_marie/ticktack'],
    ['Block_II/C/wagner_dennis/ticktack', 'Block_II/C/trinkl_simon/ticktack'],
    ['Block_II/C/wehner_romina/ticktack', 'Block_II/C/wagner_dennis/ticktack'],
    ['Block_II/C/wiedemann_florian/ticktack', 'Block_II/C/wehner_romina/ticktack'],
    ['Block_II/C/winatschek_marcel/ticktack', 'Block_II/C/wiedemann_florian/ticktack'],
    ['Block_II/C/wonka_sophia/ticktack', 'Block_II/C/winatschek_marcel/ticktack'],
    ['Block_II/C/zettelmann_kay/ticktack', 'Block_II/C/wonka_sophia/ticktack'],
    ['Block_I/B/heidle_lena', 'Block_I/B/roemmelt_alina'],
    ['Block_I/B/heinrich_finn', 'Block_I/B/heidle_lena'],
    ['Block_I/B/henke_michael', 'Block_I/B/heinrich_finn'],
    ['Block_I/B/hornung_tara', 'Block_I/B/henke_michael'],
    ['Block_I/B/just_ann-kathrin', 'Block_I/B/hornung_tara'],
    ['Block_I/B/kleiner_tobias', 'Block_I/B/just_ann-kathrin'],
    ['Block_I/B/kurzmann_paul', 'Block_I/B/kleiner_tobias'],
    ['Block_I/B/litzel_christian', 'Block_I/B/kurzmann_paul'],
    ['Block_I/B/macijauskaite_iveta', 'Block_I/B/litzel_christian'],
    ['Block_I/B/mayr_marie', 'Block_I/B/macijauskaite_iveta'],
    ['Block_I/B/pohl_jessica', 'Block_I/B/mayr_marie'],
    ['Block_I/B/roemmelt_alina', 'Block_I/B/pohl_jessica'],
]);
