var title = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'bastian aichner: '],
    ['Block_I/A/aichner_bastian/minute_shape', 'bastian aichner: '],
    ['Block_I/A/aichner_bastian/minute_typo', 'bastian aichner: '],
    ['Block_I/A/baessler_stefan/minute_color', 'stefan baessler: '],
    ['Block_I/A/baessler_stefan/minute_shape', 'stefan baessler: '],
    ['Block_I/A/baessler_stefan/minute_typo', 'stefan baessler: '],
    ['Block_I/A/binder_lisa/minute_color', 'lisa binder: '],
    ['Block_I/A/binder_lisa/minute_shape', 'lisa binder: '],
    ['Block_I/A/binder_lisa/minute_typo', 'lisa binder: '],
    ['Block_I/A/breitenbach_petra/minute_color', 'petra breitenbach: '],
    ['Block_I/A/breitenbach_petra/minute_shape', 'petra breitenbach: '],
    ['Block_I/A/breitenbach_petra/minute_typo', 'petra breitenbach: '],
    ['Block_I/A/breunig_maximilian/minute_color', 'maximilian breunig: '],
    ['Block_I/A/breunig_maximilian/minute_shape', 'maximilian breunig: '],
    ['Block_I/A/breunig_maximilian/minute_typo', 'maximilian breunig: '],
    ['Block_I/A/bui_viet-duc/minute_color', 'viet-duc bui: '],
    ['Block_I/A/bui_viet-duc/minute_shape', 'viet-duc bui: '],
    ['Block_I/A/bui_viet-duc/minute_typo', 'viet-duc bui: '],
    ['Block_I/A/christmann_tomas/minute_color', 'tomas christmann: '],
    ['Block_I/A/christmann_tomas/minute_shape', 'tomas christmann: '],
    ['Block_I/A/christmann_tomas/minute_typo', 'tomas christmann: '],
    ['Block_I/A/dieminger_annika/minute_color', 'annika dieminger: '],
    ['Block_I/A/dieminger_annika/minute_shape', 'annika dieminger: '],
    ['Block_I/A/dieminger_annika/minute_typo', 'annika dieminger: '],
    ['Block_I/A/domberger_ludwig/minute_shape', 'ludwig domberger: '],
    ['Block_I/A/domberger_ludwig/minute_typo', 'ludwig domberger: '],
    ['Block_I/A/fleischmann_anna/minute_color', 'anna fleischmann: '],
    ['Block_I/A/fleischmann_anna/minute_shape', 'anna fleischmann: '],
    ['Block_I/A/fleischmann_anna/minute_typo', 'anna fleischmann: '],
    ['Block_I/A/fliehmann_lea/minute_color', 'lea fliehmann: '],
    ['Block_I/A/fliehmann_lea/minute_shape', 'lea fliehmann: '],
    ['Block_I/A/fliehmann_lea/minute_typo', 'lea fliehmann: '],
    ['Block_I/A/fritz_nicole/minute_color', 'nicole fritz: '],
    ['Block_I/A/fritz_nicole/minute_shape', 'nicole fritz: '],
    ['Block_I/A/fritz_nicole/minute_typo', 'nicole fritz: '],
    ['Block_I/A/friz_svea/minute_color', 'svea friz: '],
    ['Block_I/A/friz_svea/minute_shape', 'svea friz: '],
    ['Block_I/A/friz_svea/minute_typo', 'svea friz: '],
    ['Block_I/A/halang_sarah/minute_color', 'sarah halang: '],
    ['Block_I/A/halang_sarah/minute_shape', 'sarah halang: '],
    ['Block_I/A/halang_sarah/minute_typo', 'sarah halang: '],
    ['Block_I/A/hartmann_jule/minute_color', 'jule hartmann: '],
    ['Block_I/A/hartmann_jule/minute_shape', 'jule hartmann: '],
    ['Block_I/A/hartmann_jule/minute_typo', 'jule hartmann: '],
    ['Block_I/A/haslauer_sarah/minute_color', 'sarah haslauer: '],
    ['Block_I/A/haslauer_sarah/minute_shape', 'sarah haslauer: '],
    ['Block_I/A/haslauer_sarah/minute_typo', 'sarah haslauer: '],
    ['Block_I/A/held_annika/minute_color', 'annika held: '],
    ['Block_I/A/held_annika/minute_shape', 'annika held: '],
    ['Block_I/A/held_annika/minute_typo', 'annika held: '],
    ['Block_II/A/aichner_bastian/miniaturen/pull', 'bastian aichner: '],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'bastian aichner: '],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'bastian aichner: '],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'stefan baessler: '],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'stefan baessler: '],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'stefan baessler: '],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'lisa binder: '],
    ['Block_II/A/binder_lisa/miniaturen/push', 'lisa binder: '],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'lisa binder: '],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'petra breitenbach: '],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'petra breitenbach: '],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'petra breitenbach: '],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'maximilian breunig: '],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'maximilian breunig: '],
    ['Block_II/A/breunig_maximilian/miniaturen/turn', 'maximilian breunig: '],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'viet-duc bui: '],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'viet-duc bui: '],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'viet-duc bui: '],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'tomas christmann: '],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'tomas christmann: '],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'tomas christmann: '],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'annika dieminger: '],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'annika dieminger: '],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'annika dieminger: '],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'ludwig domberger: '],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'ludwig domberger: '],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'ludwig domberger: '],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'anna fleischmann: '],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'anna fleischmann: '],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'anna fleischmann: '],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'lea fliehmann: '],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'lea fliehmann: '],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'lea fliehmann: '],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'nicole fritz: '],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'nicole fritz: '],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'nicole fritz: '],
    ['Block_II/A/friz_svea/miniaturen/pull', 'svea friz: '],
    ['Block_II/A/friz_svea/miniaturen/push', 'svea friz: '],
    ['Block_II/A/friz_svea/miniaturen/turn', 'svea friz: '],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'sarah halang: '],
    ['Block_II/A/halang_sarah/miniaturen/push', 'sarah halang: '],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'sarah halang: '],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'jule hartmann: '],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'jule hartmann: '],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'jule hartmann: '],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'sarah haslauer: '],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'sarah haslauer: '],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'sarah haslauer: '],
    ['Block_II/A/held_annika/miniaturen/pull', 'annika held: '],
    ['Block_II/A/held_annika/miniaturen/push', 'annika held: '],
    ['Block_II/A/held_annika/miniaturen/turn', 'annika held: '],
    ['Block_II/A/aichner_bastian/ticktack', 'bastian aichner: '],
    ['Block_II/A/baessler_stefan/ticktack', 'stefan baessler: '],
    ['Block_II/A/binder_lisa/ticktack', 'lisa binder: '],
    ['Block_II/A/breitenbach_petra/ticktack', 'petra breitenbach: '],
    ['Block_II/A/breunig_maximilian/ticktack', 'maximilian breunig: '],
    ['Block_II/A/bui_viet-duc/ticktack', 'viet-duc bui: '],
    ['Block_II/A/christmann_tomas/ticktack', 'tomas christmann: '],
    ['Block_II/A/dieminger_annika/ticktack', 'annika dieminger: '],
    ['Block_II/A/domberger_ludwig/ticktack', 'ludwig domberger: '],
    ['Block_II/A/fleischmann_anna/ticktack', 'anna fleischmann: '],
    ['Block_II/A/fliehmann_lea/ticktack', 'lea fliehmann: '],
    ['Block_II/A/fritz_nicole/ticktack', 'nicole fritz: '],
    ['Block_II/A/friz_svea/ticktack', 'svea friz: '],
    ['Block_II/A/halang_sarah/ticktack', 'sarah halang: '],
    ['Block_II/A/hartmann_jule/ticktack', 'jule hartmann: '],
    ['Block_II/A/haslauer_sarah/ticktack', 'sarah haslauer: '],
    ['Block_II/A/held_annika/ticktack', 'annika held: '],
]);
var ffw   = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'Block_I/A/aichner_bastian/minute_shape'],
    ['Block_I/A/aichner_bastian/minute_shape', 'Block_I/A/aichner_bastian/minute_typo'],
    ['Block_I/A/aichner_bastian/minute_typo', 'Block_I/A/baessler_stefan/minute_color'],
    ['Block_I/A/baessler_stefan/minute_color', 'Block_I/A/baessler_stefan/minute_shape'],
    ['Block_I/A/baessler_stefan/minute_shape', 'Block_I/A/baessler_stefan/minute_typo'],
    ['Block_I/A/baessler_stefan/minute_typo', 'Block_I/A/binder_lisa/minute_color'],
    ['Block_I/A/binder_lisa/minute_color', 'Block_I/A/binder_lisa/minute_shape'],
    ['Block_I/A/binder_lisa/minute_shape', 'Block_I/A/binder_lisa/minute_typo'],
    ['Block_I/A/binder_lisa/minute_typo', 'Block_I/A/breitenbach_petra/minute_color'],
    ['Block_I/A/breitenbach_petra/minute_color', 'Block_I/A/breitenbach_petra/minute_shape'],
    ['Block_I/A/breitenbach_petra/minute_shape', 'Block_I/A/breitenbach_petra/minute_typo'],
    ['Block_I/A/breitenbach_petra/minute_typo', 'Block_I/A/breunig_maximilian/minute_color'],
    ['Block_I/A/breunig_maximilian/minute_color', 'Block_I/A/breunig_maximilian/minute_shape'],
    ['Block_I/A/breunig_maximilian/minute_shape', 'Block_I/A/breunig_maximilian/minute_typo'],
    ['Block_I/A/breunig_maximilian/minute_typo', 'Block_I/A/bui_viet-duc/minute_color'],
    ['Block_I/A/bui_viet-duc/minute_color', 'Block_I/A/bui_viet-duc/minute_shape'],
    ['Block_I/A/bui_viet-duc/minute_shape', 'Block_I/A/bui_viet-duc/minute_typo'],
    ['Block_I/A/bui_viet-duc/minute_typo', 'Block_I/A/christmann_tomas/minute_color'],
    ['Block_I/A/christmann_tomas/minute_color', 'Block_I/A/christmann_tomas/minute_shape'],
    ['Block_I/A/christmann_tomas/minute_shape', 'Block_I/A/christmann_tomas/minute_typo'],
    ['Block_I/A/christmann_tomas/minute_typo', 'Block_I/A/dieminger_annika/minute_color'],
    ['Block_I/A/dieminger_annika/minute_color', 'Block_I/A/dieminger_annika/minute_shape'],
    ['Block_I/A/dieminger_annika/minute_shape', 'Block_I/A/dieminger_annika/minute_typo'],
    ['Block_I/A/dieminger_annika/minute_typo', 'Block_I/A/domberger_ludwig/minute_shape'],
    ['Block_I/A/domberger_ludwig/minute_shape', 'Block_I/A/domberger_ludwig/minute_typo'],
    ['Block_I/A/domberger_ludwig/minute_typo', 'Block_I/A/fleischmann_anna/minute_color'],
    ['Block_I/A/fleischmann_anna/minute_color', 'Block_I/A/fleischmann_anna/minute_shape'],
    ['Block_I/A/fleischmann_anna/minute_shape', 'Block_I/A/fleischmann_anna/minute_typo'],
    ['Block_I/A/fleischmann_anna/minute_typo', 'Block_I/A/fliehmann_lea/minute_color'],
    ['Block_I/A/fliehmann_lea/minute_color', 'Block_I/A/fliehmann_lea/minute_shape'],
    ['Block_I/A/fliehmann_lea/minute_shape', 'Block_I/A/fliehmann_lea/minute_typo'],
    ['Block_I/A/fliehmann_lea/minute_typo', 'Block_I/A/fritz_nicole/minute_color'],
    ['Block_I/A/fritz_nicole/minute_color', 'Block_I/A/fritz_nicole/minute_shape'],
    ['Block_I/A/fritz_nicole/minute_shape', 'Block_I/A/fritz_nicole/minute_typo'],
    ['Block_I/A/fritz_nicole/minute_typo', 'Block_I/A/friz_svea/minute_color'],
    ['Block_I/A/friz_svea/minute_color', 'Block_I/A/friz_svea/minute_shape'],
    ['Block_I/A/friz_svea/minute_shape', 'Block_I/A/friz_svea/minute_typo'],
    ['Block_I/A/friz_svea/minute_typo', 'Block_I/A/halang_sarah/minute_color'],
    ['Block_I/A/halang_sarah/minute_color', 'Block_I/A/halang_sarah/minute_shape'],
    ['Block_I/A/halang_sarah/minute_shape', 'Block_I/A/halang_sarah/minute_typo'],
    ['Block_I/A/halang_sarah/minute_typo', 'Block_I/A/hartmann_jule/minute_color'],
    ['Block_I/A/hartmann_jule/minute_color', 'Block_I/A/hartmann_jule/minute_shape'],
    ['Block_I/A/hartmann_jule/minute_shape', 'Block_I/A/hartmann_jule/minute_typo'],
    ['Block_I/A/hartmann_jule/minute_typo', 'Block_I/A/haslauer_sarah/minute_color'],
    ['Block_I/A/haslauer_sarah/minute_color', 'Block_I/A/haslauer_sarah/minute_shape'],
    ['Block_I/A/haslauer_sarah/minute_shape', 'Block_I/A/haslauer_sarah/minute_typo'],
    ['Block_I/A/haslauer_sarah/minute_typo', 'Block_I/A/held_annika/minute_color'],
    ['Block_I/A/held_annika/minute_color', 'Block_I/A/held_annika/minute_shape'],
    ['Block_I/A/held_annika/minute_shape', 'Block_I/A/held_annika/minute_typo'],
    ['Block_I/A/held_annika/minute_typo', 'Block_I/A/aichner_bastian/minute_color'],
    ['Block_II/A/aichner_bastian/miniaturen/pull', 'Block_II/A/aichner_bastian/miniaturen/push'],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'Block_II/A/aichner_bastian/miniaturen/turn'],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'Block_II/A/baessler_stefan/miniaturen/pull'],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'Block_II/A/baessler_stefan/miniaturen/push'],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'Block_II/A/baessler_stefan/miniaturen/turn'],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'Block_II/A/binder_lisa/miniaturen/pull'],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'Block_II/A/binder_lisa/miniaturen/push'],
    ['Block_II/A/binder_lisa/miniaturen/push', 'Block_II/A/binder_lisa/miniaturen/turn'],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'Block_II/A/breitenbach_petra/miniaturen/pull'],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'Block_II/A/breitenbach_petra/miniaturen/push'],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'Block_II/A/breitenbach_petra/miniaturen/turn'],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'Block_II/A/breunig_maximilian/miniaturen/pull'],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'Block_II/A/breunig_maximilian/miniaturen/push'],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'Block_II/A/breunig_maximilian/miniaturen/turn'],
    ['Block_II/A/breunig_maximilian/miniaturen/turn', 'Block_II/A/bui_viet-duc/miniaturen/pull'],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'Block_II/A/bui_viet-duc/miniaturen/push'],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'Block_II/A/bui_viet-duc/miniaturen/turn'],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'Block_II/A/christmann_tomas/miniaturen/pull'],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'Block_II/A/christmann_tomas/miniaturen/push'],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'Block_II/A/christmann_tomas/miniaturen/turn'],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'Block_II/A/dieminger_annika/miniaturen/pull'],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'Block_II/A/dieminger_annika/miniaturen/push'],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'Block_II/A/dieminger_annika/miniaturen/turn'],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'Block_II/A/domberger_ludwig/miniaturen/pull'],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'Block_II/A/domberger_ludwig/miniaturen/push'],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'Block_II/A/domberger_ludwig/miniaturen/turn'],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'Block_II/A/fleischmann_anna/miniaturen/pull'],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'Block_II/A/fleischmann_anna/miniaturen/push'],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'Block_II/A/fleischmann_anna/miniaturen/turn'],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'Block_II/A/fliehmann_lea/miniaturen/pull'],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'Block_II/A/fliehmann_lea/miniaturen/push'],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'Block_II/A/fliehmann_lea/miniaturen/turn'],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'Block_II/A/fritz_nicole/miniaturen/pull'],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'Block_II/A/fritz_nicole/miniaturen/push'],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'Block_II/A/fritz_nicole/miniaturen/turn'],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'Block_II/A/friz_svea/miniaturen/pull'],
    ['Block_II/A/friz_svea/miniaturen/pull', 'Block_II/A/friz_svea/miniaturen/push'],
    ['Block_II/A/friz_svea/miniaturen/push', 'Block_II/A/friz_svea/miniaturen/turn'],
    ['Block_II/A/friz_svea/miniaturen/turn', 'Block_II/A/halang_sarah/miniaturen/pull'],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'Block_II/A/halang_sarah/miniaturen/push'],
    ['Block_II/A/halang_sarah/miniaturen/push', 'Block_II/A/halang_sarah/miniaturen/turn'],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'Block_II/A/hartmann_jule/miniaturen/pull'],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'Block_II/A/hartmann_jule/miniaturen/push'],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'Block_II/A/hartmann_jule/miniaturen/turn'],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'Block_II/A/haslauer_sarah/miniaturen/pull'],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'Block_II/A/haslauer_sarah/miniaturen/push'],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'Block_II/A/haslauer_sarah/miniaturen/turn'],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'Block_II/A/held_annika/miniaturen/pull'],
    ['Block_II/A/held_annika/miniaturen/pull', 'Block_II/A/held_annika/miniaturen/push'],
    ['Block_II/A/held_annika/miniaturen/push', 'Block_II/A/held_annika/miniaturen/turn'],
    ['Block_II/A/held_annika/miniaturen/turn', 'Block_II/A/aichner_bastian/miniaturen/pull'],
    ['Block_II/A/aichner_bastian/ticktack', 'Block_II/A/baessler_stefan/ticktack'],
    ['Block_II/A/baessler_stefan/ticktack', 'Block_II/A/binder_lisa/ticktack'],
    ['Block_II/A/binder_lisa/ticktack', 'Block_II/A/breitenbach_petra/ticktack'],
    ['Block_II/A/breitenbach_petra/ticktack', 'Block_II/A/breunig_maximilian/ticktack'],
    ['Block_II/A/breunig_maximilian/ticktack', 'Block_II/A/bui_viet-duc/ticktack'],
    ['Block_II/A/bui_viet-duc/ticktack', 'Block_II/A/christmann_tomas/ticktack'],
    ['Block_II/A/christmann_tomas/ticktack', 'Block_II/A/dieminger_annika/ticktack'],
    ['Block_II/A/dieminger_annika/ticktack', 'Block_II/A/domberger_ludwig/ticktack'],
    ['Block_II/A/domberger_ludwig/ticktack', 'Block_II/A/fleischmann_anna/ticktack'],
    ['Block_II/A/fleischmann_anna/ticktack', 'Block_II/A/fliehmann_lea/ticktack'],
    ['Block_II/A/fliehmann_lea/ticktack', 'Block_II/A/fritz_nicole/ticktack'],
    ['Block_II/A/fritz_nicole/ticktack', 'Block_II/A/friz_svea/ticktack'],
    ['Block_II/A/friz_svea/ticktack', 'Block_II/A/halang_sarah/ticktack'],
    ['Block_II/A/halang_sarah/ticktack', 'Block_II/A/hartmann_jule/ticktack'],
    ['Block_II/A/hartmann_jule/ticktack', 'Block_II/A/haslauer_sarah/ticktack'],
    ['Block_II/A/haslauer_sarah/ticktack', 'Block_II/A/held_annika/ticktack'],
    ['Block_II/A/held_annika/ticktack', 'Block_II/A/aichner_bastian/ticktack'],
]);
var rew   = new Map([
    ['Block_I/A/aichner_bastian/minute_color', 'Block_I/A/held_annika/minute_typo'],
    ['Block_I/A/aichner_bastian/minute_shape', 'Block_I/A/aichner_bastian/minute_color'],
    ['Block_I/A/aichner_bastian/minute_typo', 'Block_I/A/aichner_bastian/minute_shape'],
    ['Block_I/A/baessler_stefan/minute_color', 'Block_I/A/aichner_bastian/minute_typo'],
    ['Block_I/A/baessler_stefan/minute_shape', 'Block_I/A/baessler_stefan/minute_color'],
    ['Block_I/A/baessler_stefan/minute_typo', 'Block_I/A/baessler_stefan/minute_shape'],
    ['Block_I/A/binder_lisa/minute_color', 'Block_I/A/baessler_stefan/minute_typo'],
    ['Block_I/A/binder_lisa/minute_shape', 'Block_I/A/binder_lisa/minute_color'],
    ['Block_I/A/binder_lisa/minute_typo', 'Block_I/A/binder_lisa/minute_shape'],
    ['Block_I/A/breitenbach_petra/minute_color', 'Block_I/A/binder_lisa/minute_typo'],
    ['Block_I/A/breitenbach_petra/minute_shape', 'Block_I/A/breitenbach_petra/minute_color'],
    ['Block_I/A/breitenbach_petra/minute_typo', 'Block_I/A/breitenbach_petra/minute_shape'],
    ['Block_I/A/breunig_maximilian/minute_color', 'Block_I/A/breitenbach_petra/minute_typo'],
    ['Block_I/A/breunig_maximilian/minute_shape', 'Block_I/A/breunig_maximilian/minute_color'],
    ['Block_I/A/breunig_maximilian/minute_typo', 'Block_I/A/breunig_maximilian/minute_shape'],
    ['Block_I/A/bui_viet-duc/minute_color', 'Block_I/A/breunig_maximilian/minute_typo'],
    ['Block_I/A/bui_viet-duc/minute_shape', 'Block_I/A/bui_viet-duc/minute_color'],
    ['Block_I/A/bui_viet-duc/minute_typo', 'Block_I/A/bui_viet-duc/minute_shape'],
    ['Block_I/A/christmann_tomas/minute_color', 'Block_I/A/bui_viet-duc/minute_typo'],
    ['Block_I/A/christmann_tomas/minute_shape', 'Block_I/A/christmann_tomas/minute_color'],
    ['Block_I/A/christmann_tomas/minute_typo', 'Block_I/A/christmann_tomas/minute_shape'],
    ['Block_I/A/dieminger_annika/minute_color', 'Block_I/A/christmann_tomas/minute_typo'],
    ['Block_I/A/dieminger_annika/minute_shape', 'Block_I/A/dieminger_annika/minute_color'],
    ['Block_I/A/dieminger_annika/minute_typo', 'Block_I/A/dieminger_annika/minute_shape'],
    ['Block_I/A/domberger_ludwig/minute_shape', 'Block_I/A/dieminger_annika/minute_typo'],
    ['Block_I/A/domberger_ludwig/minute_typo', 'Block_I/A/domberger_ludwig/minute_shape'],
    ['Block_I/A/fleischmann_anna/minute_color', 'Block_I/A/domberger_ludwig/minute_typo'],
    ['Block_I/A/fleischmann_anna/minute_shape', 'Block_I/A/fleischmann_anna/minute_color'],
    ['Block_I/A/fleischmann_anna/minute_typo', 'Block_I/A/fleischmann_anna/minute_shape'],
    ['Block_I/A/fliehmann_lea/minute_color', 'Block_I/A/fleischmann_anna/minute_typo'],
    ['Block_I/A/fliehmann_lea/minute_shape', 'Block_I/A/fliehmann_lea/minute_color'],
    ['Block_I/A/fliehmann_lea/minute_typo', 'Block_I/A/fliehmann_lea/minute_shape'],
    ['Block_I/A/fritz_nicole/minute_color', 'Block_I/A/fliehmann_lea/minute_typo'],
    ['Block_I/A/fritz_nicole/minute_shape', 'Block_I/A/fritz_nicole/minute_color'],
    ['Block_I/A/fritz_nicole/minute_typo', 'Block_I/A/fritz_nicole/minute_shape'],
    ['Block_I/A/friz_svea/minute_color', 'Block_I/A/fritz_nicole/minute_typo'],
    ['Block_I/A/friz_svea/minute_shape', 'Block_I/A/friz_svea/minute_color'],
    ['Block_I/A/friz_svea/minute_typo', 'Block_I/A/friz_svea/minute_shape'],
    ['Block_I/A/halang_sarah/minute_color', 'Block_I/A/friz_svea/minute_typo'],
    ['Block_I/A/halang_sarah/minute_shape', 'Block_I/A/halang_sarah/minute_color'],
    ['Block_I/A/halang_sarah/minute_typo', 'Block_I/A/halang_sarah/minute_shape'],
    ['Block_I/A/hartmann_jule/minute_color', 'Block_I/A/halang_sarah/minute_typo'],
    ['Block_I/A/hartmann_jule/minute_shape', 'Block_I/A/hartmann_jule/minute_color'],
    ['Block_I/A/hartmann_jule/minute_typo', 'Block_I/A/hartmann_jule/minute_shape'],
    ['Block_I/A/haslauer_sarah/minute_color', 'Block_I/A/hartmann_jule/minute_typo'],
    ['Block_I/A/haslauer_sarah/minute_shape', 'Block_I/A/haslauer_sarah/minute_color'],
    ['Block_I/A/haslauer_sarah/minute_typo', 'Block_I/A/haslauer_sarah/minute_shape'],
    ['Block_I/A/held_annika/minute_color', 'Block_I/A/haslauer_sarah/minute_typo'],
    ['Block_I/A/held_annika/minute_shape', 'Block_I/A/held_annika/minute_color'],
    ['Block_I/A/held_annika/minute_typo', 'Block_I/A/held_annika/minute_shape'],
    ['Block_II/A/aichner_bastian/miniaturen/pull', 'Block_II/A/held_annika/miniaturen/turn'],
    ['Block_II/A/aichner_bastian/miniaturen/push', 'Block_II/A/aichner_bastian/miniaturen/pull'],
    ['Block_II/A/aichner_bastian/miniaturen/turn', 'Block_II/A/aichner_bastian/miniaturen/push'],
    ['Block_II/A/baessler_stefan/miniaturen/pull', 'Block_II/A/aichner_bastian/miniaturen/turn'],
    ['Block_II/A/baessler_stefan/miniaturen/push', 'Block_II/A/baessler_stefan/miniaturen/pull'],
    ['Block_II/A/baessler_stefan/miniaturen/turn', 'Block_II/A/baessler_stefan/miniaturen/push'],
    ['Block_II/A/binder_lisa/miniaturen/pull', 'Block_II/A/baessler_stefan/miniaturen/turn'],
    ['Block_II/A/binder_lisa/miniaturen/push', 'Block_II/A/binder_lisa/miniaturen/pull'],
    ['Block_II/A/binder_lisa/miniaturen/turn', 'Block_II/A/binder_lisa/miniaturen/push'],
    ['Block_II/A/breitenbach_petra/miniaturen/pull', 'Block_II/A/binder_lisa/miniaturen/turn'],
    ['Block_II/A/breitenbach_petra/miniaturen/push', 'Block_II/A/breitenbach_petra/miniaturen/pull'],
    ['Block_II/A/breitenbach_petra/miniaturen/turn', 'Block_II/A/breitenbach_petra/miniaturen/push'],
    ['Block_II/A/breunig_maximilian/miniaturen/pull', 'Block_II/A/breitenbach_petra/miniaturen/turn'],
    ['Block_II/A/breunig_maximilian/miniaturen/push', 'Block_II/A/breunig_maximilian/miniaturen/pull'],
    ['Block_II/A/breunig_maximilian/miniaturen/turn', 'Block_II/A/breunig_maximilian/miniaturen/push'],
    ['Block_II/A/bui_viet-duc/miniaturen/pull', 'Block_II/A/breunig_maximilian/miniaturen/turn'],
    ['Block_II/A/bui_viet-duc/miniaturen/push', 'Block_II/A/bui_viet-duc/miniaturen/pull'],
    ['Block_II/A/bui_viet-duc/miniaturen/turn', 'Block_II/A/bui_viet-duc/miniaturen/push'],
    ['Block_II/A/christmann_tomas/miniaturen/pull', 'Block_II/A/bui_viet-duc/miniaturen/turn'],
    ['Block_II/A/christmann_tomas/miniaturen/push', 'Block_II/A/christmann_tomas/miniaturen/pull'],
    ['Block_II/A/christmann_tomas/miniaturen/turn', 'Block_II/A/christmann_tomas/miniaturen/push'],
    ['Block_II/A/dieminger_annika/miniaturen/pull', 'Block_II/A/christmann_tomas/miniaturen/turn'],
    ['Block_II/A/dieminger_annika/miniaturen/push', 'Block_II/A/dieminger_annika/miniaturen/pull'],
    ['Block_II/A/dieminger_annika/miniaturen/turn', 'Block_II/A/dieminger_annika/miniaturen/push'],
    ['Block_II/A/domberger_ludwig/miniaturen/pull', 'Block_II/A/dieminger_annika/miniaturen/turn'],
    ['Block_II/A/domberger_ludwig/miniaturen/push', 'Block_II/A/domberger_ludwig/miniaturen/pull'],
    ['Block_II/A/domberger_ludwig/miniaturen/turn', 'Block_II/A/domberger_ludwig/miniaturen/push'],
    ['Block_II/A/fleischmann_anna/miniaturen/pull', 'Block_II/A/domberger_ludwig/miniaturen/turn'],
    ['Block_II/A/fleischmann_anna/miniaturen/push', 'Block_II/A/fleischmann_anna/miniaturen/pull'],
    ['Block_II/A/fleischmann_anna/miniaturen/turn', 'Block_II/A/fleischmann_anna/miniaturen/push'],
    ['Block_II/A/fliehmann_lea/miniaturen/pull', 'Block_II/A/fleischmann_anna/miniaturen/turn'],
    ['Block_II/A/fliehmann_lea/miniaturen/push', 'Block_II/A/fliehmann_lea/miniaturen/pull'],
    ['Block_II/A/fliehmann_lea/miniaturen/turn', 'Block_II/A/fliehmann_lea/miniaturen/push'],
    ['Block_II/A/fritz_nicole/miniaturen/pull', 'Block_II/A/fliehmann_lea/miniaturen/turn'],
    ['Block_II/A/fritz_nicole/miniaturen/push', 'Block_II/A/fritz_nicole/miniaturen/pull'],
    ['Block_II/A/fritz_nicole/miniaturen/turn', 'Block_II/A/fritz_nicole/miniaturen/push'],
    ['Block_II/A/friz_svea/miniaturen/pull', 'Block_II/A/fritz_nicole/miniaturen/turn'],
    ['Block_II/A/friz_svea/miniaturen/push', 'Block_II/A/friz_svea/miniaturen/pull'],
    ['Block_II/A/friz_svea/miniaturen/turn', 'Block_II/A/friz_svea/miniaturen/push'],
    ['Block_II/A/halang_sarah/miniaturen/pull', 'Block_II/A/friz_svea/miniaturen/turn'],
    ['Block_II/A/halang_sarah/miniaturen/push', 'Block_II/A/halang_sarah/miniaturen/pull'],
    ['Block_II/A/halang_sarah/miniaturen/turn', 'Block_II/A/halang_sarah/miniaturen/push'],
    ['Block_II/A/hartmann_jule/miniaturen/pull', 'Block_II/A/halang_sarah/miniaturen/turn'],
    ['Block_II/A/hartmann_jule/miniaturen/push', 'Block_II/A/hartmann_jule/miniaturen/pull'],
    ['Block_II/A/hartmann_jule/miniaturen/turn', 'Block_II/A/hartmann_jule/miniaturen/push'],
    ['Block_II/A/haslauer_sarah/miniaturen/pull', 'Block_II/A/hartmann_jule/miniaturen/turn'],
    ['Block_II/A/haslauer_sarah/miniaturen/push', 'Block_II/A/haslauer_sarah/miniaturen/pull'],
    ['Block_II/A/haslauer_sarah/miniaturen/turn', 'Block_II/A/haslauer_sarah/miniaturen/push'],
    ['Block_II/A/held_annika/miniaturen/pull', 'Block_II/A/haslauer_sarah/miniaturen/turn'],
    ['Block_II/A/held_annika/miniaturen/push', 'Block_II/A/held_annika/miniaturen/pull'],
    ['Block_II/A/held_annika/miniaturen/turn', 'Block_II/A/held_annika/miniaturen/push'],
    ['Block_II/A/aichner_bastian/ticktack', 'Block_II/A/held_annika/ticktack'],
    ['Block_II/A/baessler_stefan/ticktack', 'Block_II/A/aichner_bastian/ticktack'],
    ['Block_II/A/binder_lisa/ticktack', 'Block_II/A/baessler_stefan/ticktack'],
    ['Block_II/A/breitenbach_petra/ticktack', 'Block_II/A/binder_lisa/ticktack'],
    ['Block_II/A/breunig_maximilian/ticktack', 'Block_II/A/breitenbach_petra/ticktack'],
    ['Block_II/A/bui_viet-duc/ticktack', 'Block_II/A/breunig_maximilian/ticktack'],
    ['Block_II/A/christmann_tomas/ticktack', 'Block_II/A/bui_viet-duc/ticktack'],
    ['Block_II/A/dieminger_annika/ticktack', 'Block_II/A/christmann_tomas/ticktack'],
    ['Block_II/A/domberger_ludwig/ticktack', 'Block_II/A/dieminger_annika/ticktack'],
    ['Block_II/A/fleischmann_anna/ticktack', 'Block_II/A/domberger_ludwig/ticktack'],
    ['Block_II/A/fliehmann_lea/ticktack', 'Block_II/A/fleischmann_anna/ticktack'],
    ['Block_II/A/fritz_nicole/ticktack', 'Block_II/A/fliehmann_lea/ticktack'],
    ['Block_II/A/friz_svea/ticktack', 'Block_II/A/fritz_nicole/ticktack'],
    ['Block_II/A/halang_sarah/ticktack', 'Block_II/A/friz_svea/ticktack'],
    ['Block_II/A/hartmann_jule/ticktack', 'Block_II/A/halang_sarah/ticktack'],
    ['Block_II/A/haslauer_sarah/ticktack', 'Block_II/A/hartmann_jule/ticktack'],
    ['Block_II/A/held_annika/ticktack', 'Block_II/A/haslauer_sarah/ticktack'],
]);
